### ISSUE TITLE
Write Unit test for getPurchaserInfoWith()

### ISSUE THREAD

**Issue by lawloretienne** [RevenueCat/purchases-android#173] opened 2020-07-12 15:52 UTC
How do I write a unit test for getPurchaserInfoWith?  It looks like the arguments to this function are lambdas. I am using the MockK library for mocking.

```
import com.revenuecat.purchases.Purchases
import com.revenuecat.purchases.getPurchaserInfoWith
import io.reactivex.Single
import javax.inject.Inject

private const val NO_ACTIVE_SUBSCRIPTION = "NO_ACTIVE_SUBSCRIPTION"

class RevenueCatRemoteDataSource @Inject constructor() {

    fun fetchActiveIAPSubscriptions(): Single<List<String>> {

        return Single.create { emitter ->
            Purchases.sharedInstance.getPurchaserInfoWith({ error ->
                emitter.onError(Throwable(error.message))
            }) { purchaserInfo ->

                if (purchaserInfo.activeSubscriptions.isEmpty()) {
                    emitter.onError(Throwable(NO_ACTIVE_SUBSCRIPTION))
                } else {
                    emitter.onSuccess(purchaserInfo.activeSubscriptions.toList())
                }
            }
        }
    }

}
```

**Comment by vegaro** [comment] 2020-07-13 18:42
Hi @lawloretienne 

I am not sure what's your problem here, but I am assuming you want to mock the `purchaserInfo` of the success lambda in `getPurchaserInfoWith`.

You have to capture the lambda using `captureLambda`, doing something like what we do here https://github.com/RevenueCat/purchases-android/blob/39bb24bdda87b4c2cc1f8a12e4ef42b7a71d018a/purchases/src/test/java/com/revenuecat/purchases/IdentityManagerTests.kt#L101

But your captured lambda will be `lambda<(PurchaserInfo) -> Unit>()` and you would pass a PurchaserInfo doing:

```kotlin
lambda<(PurchaserInfo) -> Unit>().captured.invoke(purchaserInfo)
```

Since `getPurchaserInfoWith` is an extension function on a Purchases instance, you are going to have to mock it in a different way https://github.com/mockk/mockk#extension-functions, in order to be able to capture the lambda. So your test should look something like this:

```kotlin
       val mockkInstance = mockk<Purchases>(relaxed = true)
        mockkObject(Purchases)
        every {
            Purchases.sharedInstance
        } returns mockkInstance

        mockkStatic("com.revenuecat.purchases.ListenerConversionsKt")

        every {
            mockkInstance.getPurchaserInfoWith(any(), captureLambda())
        } answers {
            lambda<(PurchaserInfo) -> Unit>().captured.invoke(mockk<PurchaserInfo>(relaxed = true))
        }
```


Since this is not an issue with this library, and definitely not a bug, I am going to close this issue. You might find better help on how to use mockk in StackOverflow. 

If I have misunderstood your request feel free to reopen and clarify what's the particular issue you are finding in our SDK.

Thanks!

**Closed** 2020-07-13 18:42 UTC
Labels: bug

**Comment by lawloretienne** [comment] 2020-07-14 00:44
Thanks for that helpful info.  I didnt know about captureLambda().  Very helpful. I will give this a try.

**Comment by lawloretienne** [comment] 2020-07-14 01:39
Yep that worked. Here is what my test class looks like now :

```
class RevenueCatRemoteDataSourceTest : BaseTest() {

    @RelaxedMockK
    lateinit var purchases: Purchases

    @RelaxedMockK
    lateinit var purchaserInfo: PurchaserInfo

    private lateinit var revenueCatRemoteDataSource: RevenueCatRemoteDataSource

    @BeforeEach
    override fun setUp() {
        super.setUp()
        revenueCatRemoteDataSource = RevenueCatRemoteDataSource()
    }

    @Test
    fun `fetchActiveIAPSubscriptions should return activiteSubscriptions when there are active subscriptions`() {
        val iapSubscriptions = setOf(
            faker.lorem().word(),
            faker.lorem().word()
        )

        mockkObject(Purchases)
        every { Purchases.sharedInstance } returns purchases

        mockkStatic("com.revenuecat.purchases.ListenerConversionsKt")

        every {
            purchases.getPurchaserInfoWith(any(), captureLambda())
        } answers {
            lambda<(PurchaserInfo) -> Unit>().captured.invoke(purchaserInfo)
        }

        every {purchaserInfo.activeSubscriptions }.answers { iapSubscriptions }

        revenueCatRemoteDataSource.fetchActiveIAPSubscriptions()
            .test()
            .assertValue(iapSubscriptions.toList())
    }

    @Test
    fun `fetchActiveIAPSubscriptions should return error when no active subscriptions`() {
        mockkObject(Purchases)
        every { Purchases.sharedInstance } returns purchases

        mockkStatic("com.revenuecat.purchases.ListenerConversionsKt")

        every {
            purchases.getPurchaserInfoWith(any(), captureLambda())
        } answers {
            lambda<(PurchaserInfo) -> Unit>().captured.invoke(purchaserInfo)
        }

        revenueCatRemoteDataSource.fetchActiveIAPSubscriptions()
            .test()
            .assertError(Throwable::class.java)
    }

}
```
