### ISSUE TITLE
[Bug] Incorrect Revenuecat behavior when using logIn

### ISSUE THREAD

**Issue by mikezliu** [RevenueCat/purchases-android#466] opened 2022-02-01 07:58 UTC
- [ X ] I have updated Purchases SDK to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [ X ] I have searched the [Community](https://community.revenuecat.com)
- [ X ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ X ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**

I think the new way of transferring and aliasing user IDs via the logIn api (see https://docs.revenuecat.com/docs/user-ids) has some flaws and could use revisiting.

This scenario can happen:
1. User installs app and purchases subscription
2. User creates an account (AccountA), and uses logIn. Revenuecat will now use the AccountA for the account and alias the anonymous ID

Design issue #1: The user then installs the app on a 2nd device. They click 'restore purchases' (before sign in, or the app does it on first time startup to restore purchases in their account). This will transfer their purchases from part 2, into a new anonymous ID. So AccountA will lose access to the purchase. See https://docs.revenuecat.com/docs/restoring-purchases ("If an anonymous ID restores and the owner of the receipt is an identified App User ID, we will resort to the specified restore behavior and transfer the receipt to the anonymous user.")

Design issue #2: The user on the 2nd device then logs in (using logIn API). Now they lose access to their subscription. This is because AccountA is already aliased with an anonymous ID on the first device. See https://docs.revenuecat.com/docs/user-ids 
("logIn() behavior - see 3rd row about Anonymous ID, App User ID alreadyt exists, App User ID has anonymous alias => no alias created"). Now none of their accounts on either devices have access to the subscription.

Design issue #3: Similar to design issue #1, but the user doesn't sign in on their 2nd device. When they click restore purchase on device #2, the subscription is transferred to their Anonymous ID and Account A loses access. They then click restore purchase on device #1 and Account A gets access again but their device #2 loses access. I've seen some accounts have subscription access bounce back and forth like this and I have to tell the user to sign in on the same account on all devices (and it's not a supported scenario for some devices to not be signed in from inside the app). But many users probably don't reach out to me about this issue and just post bad reviews or stop subscribing.

I really think these issues are major design flaws. I spent a good chunk of the afternoon debugging why users were complaining about losing access to their subscriptions, and I can see how they can be confused from these two results. I think in both cases, aliasing should be done instead of a transfer, or at least provide the developer a way to alias (It's not possible for me to switch from 'Transfer' backend behavior back to the legacy alias behavior).

I'm working around design issue #2 by checking whether the user is anonymous or not before calling logIn. If they are anonymous, I use the deprecated alias API.

1. Environment
   1. Platform: Android and iOS
   2. SDK version: 3.3
   3. OS version: Android 11, iOS 15
   4. Android Studio version: 2020.3.1 
   5. How widespread is the issue. Percentage of devices affected. 100%
Debug logs that reproduce the issue
N/A
Steps to reproduce, with a description of expected vs. actual behavior
N/A
Other information (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
N/A

Additional context
N/A - see above description

**Comment by codykerns** [comment] 2022-02-02 15:22
Hey @mikezliu, thanks for the detailed feedback here! Just to clarify, are accounts optional for your app?

In general, we transfer receipts between user accounts that aren't connected, because we don't have a way of knowing beforehand if that new user ID (most of the time anonymous IDs for new installation, etc.) has their receipt already synced to a different user ID.

> Design issue #1: The user then installs the app on a 2nd device. They click 'restore purchases' (before sign in, or the app does it on first time startup to restore purchases in their account). This will transfer their purchases from part 2, into a new anonymous ID. So AccountA will lose access to the purchase. See https://docs.revenuecat.com/docs/restoring-purchases ("If an anonymous ID restores and the owner of the receipt is an identified App User ID, we will resort to the specified restore behavior and transfer the receipt to the anonymous user.")

Are you able to require the user to sign-in before allowing them to restore purchases? If not, we opt to treat it as a separate user claiming the receipt since it's a brand new anonymous identifier with no other context. Or maybe a better option, can you explain this to your customer? E.g., "if you have an existing account, please log in, otherwise restore purchases"

> Design issue #2: The user on the 2nd device then logs in (using logIn API). Now they lose access to their subscription. This is because AccountA is already aliased with an anonymous ID on the first device. See https://docs.revenuecat.com/docs/user-ids

Yeah, I see what you're saying here. A workaround might be to call `syncPurchases` after a log-in, so you can ensure the identified user ID always has the latest receipt synced for that user. Since we already transferred the receipt to a different user ID, it's expected that the previously identified user no longer has access. It's not ideal in this case, understandably, so you'll want to re-sync the receipt upon login.

> Design issue #3: Similar to design issue #1, but the user doesn't sign in on their 2nd device. When they click restore purchase on device #2, the subscription is transferred to their Anonymous ID and Account A loses access. They then click restore purchase on device #1 and Account A gets access again but their device #2 loses access. I've seen some accounts have subscription access bounce back and forth like this and I have to tell the user to sign in on the same account on all devices (and it's not a supported scenario for some devices to not be signed in from inside the app). But many users probably don't reach out to me about this issue and just post bad reviews or stop subscribing.

Yeah, this is expected behavior so aliasing doesn't get out of control. These are effectively different users if they aren't identified with your own user identifier, so we have to pass subscriptions back and forth.

Optional user accounts can definitely add a bit of complexity and cause some odd behavior, but in general we feel the behavior is in a good place. That being said, I'd be happy to share this feedback with the team as we're always looking to make improvements.

**Comment by mikezliu** [comment] 2022-02-02 15:43
Thanks for the response! Yes user accounts are optional in my app, and purchasing an item doesn’t require creating an account (from my AB tests, requiring sign in/sign up resulted in a large drop off in subscription rates).

Maybe another way is if you allowed us to tweak in what cases transfer or alias is done, or bring back the old alias method as a selectable option. I realize the new method is supposed to guarantee only one account has access, but can cause some user confusion if the app has optional sign in.

**Comment by codykerns** [comment] 2022-02-04 21:17
Hey @mikezliu! Understood - thanks for the feedback here. I'm going to work on improving our documentation for handling these types of cases (optional user accounts, etc.), and detailing best practices to improve the experience as I definitely think these are valid points. I'll close this out for now, but feel free to reopen if you need to!

**Closed by codykerns** 2022-02-04 21:17 UTC
Labels: bug, triaged
