### ISSUE TITLE
Service not registered issue with AdvertisingConnection

### ISSUE THREAD

**Issue by Thib75** [RevenueCat/purchases-android#98] opened 2020-01-21 17:23 UTC
Hi, I have this issue with a lot of my users. It is maybe related to the lifecycle of the app? Thanks for your help :)

## The line of code causing the issue in the app onCreate :
```java
 AppsFlyerLib.getInstance().init("***************", new AppsFlyerConversionListener() {
            @Override
            public void onInstallConversionDataLoaded(Map<String, String> conversionData) {
                Purchases.addAttributionData(conversionData, Purchases.AttributionNetwork.APPSFLYER, AppsFlyerLib.getInstance().getAppsFlyerUID(App.this));
            }
}
```

## version :

`com.revenuecat.purchases:purchases:2.4.2`

## Crash report :

> Fatal Exception: java.lang.IllegalArgumentException
> Service not registered: com.revenuecat.purchases.util.AdvertisingIdClient$AdvertisingConnection@2d58707
> 
> android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1671)
> android.content.ContextWrapper.unbindService (ContextWrapper.java:730)
> com.revenuecat.purchases.util.AdvertisingIdClient$getAdvertisingIdInfo$1.run (AdvertisingIdClient.java:48)
> java.lang.Thread.run (Thread.java:764)
>

**Comment by Francescu** [comment] 2020-01-27 09:38
Any update? It's our #1 crash 😰

**Comment by vegaro** [comment] 2020-01-29 23:16
Thanks for reporting. I have a fix for this ready. It will go out in the next release.

Sorry about that!

**Comment by vegaro** [comment] 2020-02-03 19:55
The fix has been released. Please let us know if you are still seeing the same issue. Thanks!!

**Comment by Thib75** [comment] 2020-02-19 13:38
Hi @vegaro and thanks for your fix :)

**Comment by vegaro** [comment] 2020-02-21 00:25
Thanks for updating back. Did the numbers drop at all? I am taking a look at it again.

**Comment by Thib75** [comment] 2020-02-24 10:01
Hi @vegaro the numbers of crashes seems to have drop, but it is difficult to know the exact number, as we didn't released to 100% of our users :)

**Comment by Francescu** [comment] 2020-02-26 10:49
@vegaro Should this issue be reopened?

**Comment by vegaro** [comment] 2020-02-26 19:03
Yes, sorry my bad. We are finishing a new feature for RevenueCat and we will include another fix for this in the next release.

I am still trying to wrap my head around how https://github.com/RevenueCat/purchases-android/blob/master/purchases/src/main/java/com/revenuecat/purchases/util/AdvertisingIdClient.kt#L48 can be hit without binding the service. 

For reference, I am going to link this here https://stackoverflow.com/a/48589803/1148405

**Comment by Thib75** [comment] 2020-03-10 13:17
Hi @vegaro, any update regarding this issue? 😰

**Comment by vegaro** [comment] 2020-03-10 19:25
Not yet, but planning on releasing a fix this week for it

**Comment by vegaro** [comment] 2020-03-11 00:08
@Thib75 @Francescu are you already including Play Services Ads in your app? I am thinking about changing the way we automatically collect the Google Advertising Id and use the officially provided library included in the Play Services Ads instead of the way we are doing it right now (which is clearly giving issues)

**Comment by Thib75** [comment] 2020-03-11 10:29
Hi @vegaro, no we don't use Play Services Ads in our app :)

**Comment by vegaro** [comment] 2020-03-13 21:25
Sorry it got automatically closed when merging https://github.com/RevenueCat/purchases-android/pull/124 

I hope that fixes it. I haven't been able to reproduce it and after looking a lot at different posibilities, my hope is that by posting the `unbindService` to the main thread, it will be executed after whatever the `bindService` is doing asynchronously on the main thread.

Please let us know what the numbers look like when you guys update. We are planning on doing a release on Monday.

I never really asked, but can you see any pattern on the devices that are getting this error? (OS versions, manufacturers, etc.)

Thanks for being patient!

**Comment by Thib75** [comment] 2020-03-25 14:55
Hi @vegaro 👋 

Thanks a lot for all these feedbacks.

About patterns, regarding the devices, the android version or the state of when the crash occurs (background or foreground), we haven't noticed any particular metrics that could help 😞 

I have seen the new release 2.4.3, but because we have already migrate to the 3 version, is your fix also present in the last release 3.1.0 ?

Thanks for your help 😊

**Comment by vegaro** [comment] 2020-03-25 22:33
Hi @Thib75 !

`2.4.3` doesn't have the fix, that's an update on top of that fixes a critical bug regarding compatibility with AppsFlyer on `2.4.2`. GitHub thinks that's the most recent version since it's the latest tag, but the most recent version is `3.1.0`

`3.1.0` should have the most recent fix :)

**Comment by Thib75** [comment] 2020-03-26 09:18
OK perfect 👌 

We will let you know if we still have the issue in 3.1.0 😊 

Thanks !

**Comment by vegaro** [comment] 2020-04-28 21:48
@Thib75 any news on this?

**Comment by Thib75** [comment] 2020-05-04 13:56
Hi @vegaro 👋

Unfortunately, we still have the issue even in 3.1.0

**This is the crash report update :** 

> Fatal Exception: java.lang.IllegalArgumentException
Service not registered: com.revenuecat.purchases.util.AdvertisingIdClient$AdvertisingConnection@1ffdb86
android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1671)
android.content.ContextWrapper.unbindService (ContextWrapper.java:730)
com.revenuecat.purchases.util.AdvertisingIdClient$getAdvertisingIdInfo$1$2.run (AdvertisingIdClient.java:50)
android.os.Handler.handleCallback (Handler.java:873)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)

**Comment by vegaro** [comment] 2020-05-06 16:50
Thanks for the update. We will look into other possible solutions and keep this updated

**Comment by Thib75** [comment] 2020-05-11 15:55
Hi @vegaro, after some investigation, the numbers of crashes per session has raised by a factor 3 !

**For around 5M sessions we have:**
0.54% crash per session in 3.0.5
1.49% crash per session in 3.1.0

Hope that this information will help you a little :)

Also, do you think that we may have a wrong use of the library? Do you encounter the same issue with other company?

Thanks !

**Comment by Thib75** [comment] 2020-05-19 16:16
Hi @vegaro, after some time to dig a little deeper, we have finally found the origin of the issue 😀

In short, the problem was related to the unbind of a service already unbound. To fix this you could simply catch the error, or add some checks to detect if the service had already be unbound or not.

Indeed, a service can be unbound from the developer but sometimes by the system itself. In our case, we initialized the Purchases object with an activity context, during SplashScreen. When this activity was destroyed, the system automatically unbind services attached to it. After initializing the Purchases with the application context, the problem disappeared 👍 

Hoping that these informations are clear enough, don't hesitate to ping me if you need more details about it.

Thanks again for your time and your help 😊

**Comment by vegaro** [comment] 2020-05-26 19:47
Thank you for the follow up. That makes a lot of sense. I think we have a bug here https://github.com/RevenueCat/purchases-android/blob/develop/purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt#L1330 since we are not getting the `applicationContext` when initializing the SDK, even though we require one in https://github.com/RevenueCat/purchases-android/blob/develop/purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt#L1308. It actually looks like the `require()` doesn't work if you say that you were initializing with an Activity context without any issue.

I will take a look as soon as I finish some other stuff I have pending.

Thanks again for the follow up, we really appreciate it 😸

**Comment by vegaro** [comment] 2020-05-29 21:40
I just merged the fix and it should go out in the next release

**Closed** 2020-05-29 21:39 UTC
Labels: bug
